<?php
use CRM_Shares_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Zero_balance_holdings',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Zero_balance_holdings',
        'label' => E::ts('Zero balance holdings'),
        'api_entity' => 'ShareHolding',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'contact_id.display_name',
            'ShareHolding_ShareIssue_issue_id_01.society_id.display_name',
            'issue_id.name',
            'interest_choice_id:label',
            'ShareHolding_ShareAccount_holding_id_01.balance',
            'ShareHolding_ShareAccount_holding_id_03.balance',
          ],
          'orderBy' => [],
          'where' => [
            [
              'ShareHolding_ShareAccount_holding_id_01.balance',
              '=',
              '0',
            ],
            [
              'ShareHolding_ShareAccount_holding_id_01.balance',
              '=',
              '0',
            ],
          ],
          'groupBy' => [],
          'join' => [
            [
              'ShareIssue AS ShareHolding_ShareIssue_issue_id_01',
              'LEFT',
              [
                'issue_id',
                '=',
                'ShareHolding_ShareIssue_issue_id_01.id',
              ],
            ],
            [
              'ShareAccount AS ShareHolding_ShareAccount_holding_id_01',
              'INNER',
              [
                'id',
                '=',
                'ShareHolding_ShareAccount_holding_id_01.holding_id',
              ],
              [
                'ShareHolding_ShareAccount_holding_id_01.account_type_id:name',
                '=',
                '"holding"',
              ],
            ],
            [
              'ShareAccount AS ShareHolding_ShareAccount_holding_id_02',
              'INNER',
              [
                'id',
                '=',
                'ShareHolding_ShareAccount_holding_id_02.holding_id',
              ],
              [
                'ShareHolding_ShareAccount_holding_id_02.account_type_id:name',
                '=',
                '"cash"',
              ],
            ],
            [
              'ShareAccount AS ShareHolding_ShareAccount_holding_id_03',
              'INNER',
              [
                'id',
                '=',
                'ShareHolding_ShareAccount_holding_id_03.holding_id',
              ],
              [
                'ShareHolding_ShareAccount_holding_id_03.account_type_id:name',
                '=',
                '"payable"',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Zero_balance_holdings_SearchDisplay_Zero_balance_holdings_tab',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Zero_balance_holdings_tab',
        'label' => E::ts('Zero balance holdings tab'),
        'saved_search_id.name' => 'Zero_balance_holdings',
        'type' => 'table',
        'settings' => [
          'description' => '',
          'sort' => [
            [
              'ShareHolding_ShareIssue_issue_id_01.society_id.display_name',
              'ASC',
            ],
            ['issue_id.name', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'ShareHolding_ShareIssue_issue_id_01.society_id.display_name',
              'dataType' => 'String',
              'label' => E::ts('Society'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'ShareHolding_ShareIssue_issue_id_01.society_id',
                'target' => '',
              ],
              'title' => E::ts('View Society'),
            ],
            [
              'type' => 'field',
              'key' => 'issue_id.name',
              'dataType' => 'String',
              'label' => E::ts('Issue'),
              'sortable' => TRUE,
              'title' => E::ts('View Issue'),
              'link' => [
                'path' => '',
                'entity' => 'ShareIssue',
                'action' => 'view',
                'join' => 'issue_id',
                'target' => '',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'interest_choice_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Interest Choice'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'ShareHolding_ShareAccount_holding_id_01.balance',
              'dataType' => 'Float',
              'label' => E::ts('Capital'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/shares/account/entries#?account_type_id=2&holding_id=[ShareHolding_ShareAccount_holding_id_01.holding_id.id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => 'crm-popup',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'ShareHolding_ShareAccount_holding_id_03.balance',
              'dataType' => 'Float',
              'label' => E::ts('Payable'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/shares/account/entries#?account_type_id=3&holding_id=[ShareHolding_ShareAccount_holding_id_01.holding_id.id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => 'crm-popup',
              ],
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'ShareHolding',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Details'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'path' => 'civicrm/shares/holding/transfer?hid=[id]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Transfer'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'path' => 'civicrm/shares/holding/capital-repayment?hid=[id]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Capital Repayment'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'path' => 'civicrm/shares/holding/payment?hid=[id]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Payment'),
                  'style' => 'default',
                  'condition' => [
                    'ShareHolding_ShareAccount_holding_id_03.balance',
                    '>',
                    '0',
                  ],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => ['table', 'table-striped'],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Zero_balance_holdings_SearchDisplay_Zero_balance_register',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Zero_balance_register',
        'label' => E::ts('Zero balance register'),
        'saved_search_id.name' => 'Zero_balance_holdings',
        'type' => 'table',
        'settings' => [
          'description' => '',
          'sort' => [
            [
              'contact_id.sort_name',
              'ASC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'contact_id.display_name',
              'dataType' => 'String',
              'label' => E::ts('Holder'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'contact_id',
                'target' => '',
              ],
              'title' => E::ts('View Contact'),
            ],
            [
              'type' => 'field',
              'key' => 'interest_choice_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Interest Choice'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'ShareHolding_ShareAccount_holding_id_01.balance',
              'dataType' => 'Float',
              'label' => E::ts('Capital'),
              'sortable' => TRUE,
              'rewrite' => '',
              'link' => [
                'path' => 'civicrm/shares/account/entries#?account_type_id=2&holding_id=[ShareHolding_ShareAccount_holding_id_01.holding_id.id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => 'crm-popup',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'ShareHolding_ShareAccount_holding_id_03.balance',
              'dataType' => 'Float',
              'label' => E::ts('Payable'),
              'sortable' => TRUE,
              'link' => [
                'path' => 'civicrm/shares/account/entries#?account_type_id=3&holding_id=[ShareHolding_ShareAccount_holding_id_01.holding_id.id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => 'crm-popup',
              ],
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'ShareHolding',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Details'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'path' => 'civicrm/shares/holding/transfer?hid=[id]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Transfer'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'path' => 'civicrm/shares/holding/repayment?hid=[id]',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Repayment'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => ['download'],
          'classes' => ['table', 'table-striped'],
          'headerCount' => FALSE,
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
